import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>EXRAZER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="introduce" content="Thianthanet Mikula" />
        <link rel="icon" href="/icon.png" />
        <link rel = "stylesheet" href = "globals.css"/>
      </Head>

      <div className = "container flex flex-col mx-auto">
        <Image src = "/Profile.png" width = {350} height = {350} alt = "logo"></Image>
        <h1 className="text-4xl font-bold underline italic text-center pt-6 pb-8">
          Thianthanet Mikula
        </h1>
        <h1 className = "text-center text-xl text-opacity-50 pb-5">| Front-End Developer |</h1>
        <div className = "font-bold text-3xl text-center pt-15">
        Faculty of Computer Engineering
        </div>
        <div className = "text-center text-3xl pt-5 font-bold">
          NARESUAN UNIVERSITY
        </div>

        <div className = "social m-5">
          <a href = "https://www.facebook.com/ZeRoXKunG/">
            <Image className = "pr-3 pt-2" src = "/facebook.png" width = {50} height = {50} alt = "logo"></Image>
          </a>
          
          <a href = "https://www.youtube.com/channel/UCZ0_HSabyIfThrsnjkbLf0g">
            <Image className = "pr-3 pt-2" src = "/youtube.png" width = {50} height = {50} alt = "logo"></Image>
          </a>
          
          <a href = "https://www.tiktok.com/@thianthanet?_t=8b3M4HKgzsg&_r=1&fbclid=IwAR0A42mYrpRWzxhAgv0eMbknKEmyqYkhV1Vx8oqcz51KaGCrdtsPQQAjywE">
            <Image className = "pr-3 pt-2" src = "/tik-tok.png" width = {50} height = {50} alt = "logo"></Image>
          </a>

          <a href = "https://www.instagram.com/ttnxt_di/">
            <Image className = "pr-3 pt-2" src = "/instagram.png" width = {50} height = {50} alt = "logo"></Image>
          </a>
          <a href = "https://github.com/EXRAZER">
            <Image className = "pr-3 pt-2" src = "/github.png" width = {50} height = {50} alt = "logo"></Image>
          </a>

        </div>
      </div>
    </>
  )
}
